// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbXbe08W6uvfm--igMUgOvTU9U2UvEPxY',
    appId: '1:150244663945:web:bb9c66af576a5fd874dc58',
    messagingSenderId: '150244663945',
    projectId: 'party-haan-b0ae0',
    authDomain: 'party-haan-b0ae0.firebaseapp.com',
    storageBucket: 'party-haan-b0ae0.appspot.com',
    measurementId: 'G-2DBD1HMQGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeONf2tRgJAJZE1FAtSBtOn0JTQ9_Nmzo',
    appId: '1:150244663945:android:6ea8b4b902df216e74dc58',
    messagingSenderId: '150244663945',
    projectId: 'party-haan-b0ae0',
    storageBucket: 'party-haan-b0ae0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0e7u_4yhBShXp3U146Edv27RQfbXq964',
    appId: '1:150244663945:ios:a689a698be60841574dc58',
    messagingSenderId: '150244663945',
    projectId: 'party-haan-b0ae0',
    storageBucket: 'party-haan-b0ae0.appspot.com',
    iosClientId: '150244663945-677ns1a471f67em0ftrkvpvnpkqa10qk.apps.googleusercontent.com',
    iosBundleId: 'n',
  );
}
